os: osx
language: objective-c
before_install:
  - brew tap sevki/homebrew-gcc_cross_compilers
  - brew tap Homebrew/homebrew-core
env:
  - ARCH=x86_64
  - ARCH=arm
  - ARCH=i586
script:
  - sh test.sh
branches:
  only:
    - master
notifications:
  recipients:
    - s@sevki.org
  email:
    on_success: always
    on_failure: always
